=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q1.dtd
<!ELEMENT Personalinfo (RollNo,Name,Address,Mobile,DoB,Age,Qualification)>
	<!ELEMENT RollNo (#PCDATA)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT Mobile (#PCDATA)>
	<!ELEMENT DoB (#PCDATA)>
	<!ELEMENT Age (#PCDATA)>
	<!ELEMENT Qualification (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/aa2_1.xml
<?xml version="1.0" standalone="no"?>
	<!DOCTYPE Personalinfo SYSTEM "Q1.dtd">
	<Personalinfo>
		<RollNo>1</RollNo>
		<Name>cdc</Name>
		<Address>csc</Address>
		<Mobile>2323</Mobile>
		<DoB>2005</DoB>
		<Age>15</Age>
		<Qualification>Is</Qualification>
	</Personalinfo>
