=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q4.dtd
<!ELEMENT Student (Name,Personalinfo,Result)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Personalinfo (Address,Birthdate,Gender,Mobile)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender (Male|Female)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT Result (Total,Percentage,Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass|First|Dist|Second|Fail)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/ass2_4.xml
<?xml version="1.0" standalone="no"?>
	<!DOCTYPE Student SYSTEM "Q4.dtd">
	<Student>
		<Name>vansh</Name>
		<Personalinfo>
			<Address>dd</Address>
			<Birthdate>12</Birthdate>
			<Gender><Male></Male></Gender>
			<Mobile>1223</Mobile>
		</Personalinfo>
		<Result>
			<Total>700</Total>
			<Percentage>100</Percentage>
			<Grade><Pass></Pass></Grade>
		</Result>
	</Student>
