=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q6.dtd
<!ELEMENT Student (Name,Id,Plan)>
	<!ELEMENT Name (fname,lname)>
	<!ELEMENT fname (#PCDATA)>
	<!ELEMENT lname (#PCDATA)>
	<!ELEMENT Id (#PCDATA)>
	<!ELEMENT Plan (courses*)>
	<!ELEMENT courses (course)>
	<!ATTLIST courses year CDATA #REQUIRED>
	<!ELEMENT course (name,Shortname,Record*)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT Shortname (#PCDATA)>
	<!ELEMENT Record (Grade,Date)>
	<!ELEMENT Grade (#PCDATA)>
	<!ELEMENT Date (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/ass2_6.xml
<?xml version="1.0" standalone="no"?>
	<!DOCTYPE Student SYSTEM "Q6.dtd">
	<Student>
		<Name>
			<fname>Vansh</fname>
			<lname>Vora</lname>
		</Name>
		<Id>1</Id>
		<Plan>
			<courses year="2004">
				<course>
					<name>xc</name>
					<Shortname>ccd</Shortname>
						<Record>
							<Grade></Grade>
							<Date></Date>
						</Record>
				</course>
			</courses>
		</Plan>
	</Student>
