=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q7.dtd
<!ELEMENT Email (from,to,content)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT content (person,exercises)*>
<!ELEMENT person (#PCDATA)>
<!ELEMENT exercises (exercise*,course)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT exercise (topic,discription)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT discription (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/ass2_7.xml
<?xml version="1.0"?>
	<!DOCTYPE Email SYSTEM "Q7.dtd">
	<Email>
		<from>vansh</from>
		<to>sarthak</to>
		<content>
			<person>sdf</person>
			<exercises>
				<exercise>
					<topic>ds</topic>
					<discription>ss</discription>
				</exercise>
				<course>cd</course>
			</exercises>
		</content>
	</Email>
