=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q8.dtd
<!ELEMENT Student (rollno,name,marks,rank)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT marks (webtec|xml|j2ee|ns)>
<!ELEMENT webtec (#PCDATA)>
<!ELEMENT xml (#PCDATA)>
<!ELEMENT j2ee (#PCDATA)>
<!ELEMENT ns (#PCDATA)>
<!ELEMENT rank (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/ass2_8.xml
<?xml version="1.0"?>
	<!DOCTYPE Student SYSTEM "Q8.dtd">
		<Student>
			<rollno>1</rollno>
			<name>vdfad</name>
			<marks>
				<webtec>er</webtec>
				<xml>eff</xml>
				<j2ee>fef</j2ee>
				<ns>ef</ns>
			</marks>
			<rank>fdf</rank>
		</Student>
