=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/Q9.dtd
<!ELEMENT Letter (contact+,salutation,paragraph,closing,signature)>
<!ELEMENT contact (name,address,city,pin,state,flag)>
<!ATTLIST contact type  CDATA #FIXED "sender" >
<!ELEMENT sender  (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT flag EMPTY>
<!ATTLIST flag Gender (Male|Female) "Male">
<!ELEMENT salutation (#PCDATA)>
<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT closing (#PCDATA)>
<!ELEMENT signature (#PCDATA)>

=== Vansh-vora/Sem-3-Practical-Assignments/XML Assignments/unit 2/ass2_9.xml
<?xml version="1.0"?>
	<!DOCTYPE Letter SYSTEM "Q9.dtd">
	<Letter>
		<contact type="sender">
			<name>sds</name>
			<address>sd</address>
			<city>sd</city>
			<pin>sd</pin>
			<state>s</state>
			<flag Gender="Male"></flag>
		</contact>
		<salutation>scc</salutation>
		<paragraph>cdvd</paragraph>
		<closing>cd</closing>
		<signature>scs</signature>
	</Letter>
